'use no memo'

import type { EditorThemeClasses } from 'lexical'

export const commentEditorTheme: EditorThemeClasses = {
  paragraph: 'mb-1 text-sm',
  text: {
    bold: 'font-bold',
    italic: 'italic',
    underline: 'underline',
    strikethrough: 'line-through',
    code: 'rounded bg-muted px-1 py-0.5 font-mono text-xs',
  },
  list: {
    ul: 'list-disc ml-4 text-sm',
    ol: 'list-decimal ml-4 text-sm',
    listitem: 'ml-2',
    nested: {
      listitem: 'list-none',
    },
  },
  quote: 'border-l-2 border-muted-foreground/30 pl-3 italic text-muted-foreground text-sm',
  code: 'block rounded-md bg-muted p-3 font-mono text-xs overflow-x-auto',
  codeHighlight: {
    atrule: 'lexical-hl-atrule',
    attr: 'lexical-hl-attr',
    boolean: 'lexical-hl-boolean',
    builtin: 'lexical-hl-builtin',
    cdata: 'lexical-hl-cdata',
    char: 'lexical-hl-char',
    class: 'lexical-hl-class',
    'class-name': 'lexical-hl-class',
    comment: 'lexical-hl-comment',
    constant: 'lexical-hl-constant',
    deleted: 'lexical-hl-deleted',
    doctype: 'lexical-hl-cdata',
    entity: 'lexical-hl-constant',
    function: 'lexical-hl-function',
    important: 'lexical-hl-important',
    inserted: 'lexical-hl-inserted',
    keyword: 'lexical-hl-keyword',
    namespace: 'lexical-hl-cdata',
    number: 'lexical-hl-number',
    operator: 'lexical-hl-operator',
    prolog: 'lexical-hl-cdata',
    property: 'lexical-hl-property',
    punctuation: 'lexical-hl-punctuation',
    regex: 'lexical-hl-regex',
    selector: 'lexical-hl-selector',
    string: 'lexical-hl-string',
    symbol: 'lexical-hl-constant',
    tag: 'lexical-hl-tag',
    url: 'lexical-hl-url',
    variable: 'lexical-hl-variable',
  },
  link: 'text-primary underline cursor-pointer',
  mark: 'cursor-pointer rounded-sm bg-primary/15 px-0.5 text-foreground ring-1 ring-primary/20 transition-colors data-[active=true]:bg-primary/30 data-[active=true]:ring-primary/60',
  markOverlap: 'bg-accent/70 ring-accent',
  heading: {
    h1: 'text-xl font-bold mb-2',
    h2: 'text-lg font-bold mb-1',
    h3: 'text-base font-bold mb-1',
  },
}
